version: "3.8"

services:
  app:
    build: .
    ports:
      - "80:3000"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: 5432
      DB_NAME: todo
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD}



